### PR TITLE
Delete .npmrc

### PR DESCRIPTION
**Pull request by gomberg5264**

### CODE REVIEW

**Comment by crock** [comment]
@gomberg5264 Why are you deleting .npmrc? Is there a good reason for deleting it?

**Comment by gomberg5264** [comment]
Sorry I did not mean to delete the file when I was trying to deploy it on Netlify for my personal use it did not work. So I was trying to figure it out. And debug the issue.

**Comment by crock** [comment]
> Sorry I did not mean to delete the file when I was trying to deploy it on Netlify for my personal use it did not work. So I was trying to figure it out. And debug the issue.

I use Font Awesome Pro icons, so you need a license key which you add to your Netlify environment variables. the .npmrc is necessary so it can pull down the pro version of the library which is private.

**Comment by crock** [comment]
@gomberg5264 see my reply above

**Pull request closed without merging**
